name: Contiouous Deployment 
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write 
jobs: 
  deplays:
  runs-on: ubuntu-lastest
  environment:
    name: github-pages

    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
        path:

      - uses: actions/deploy-pages@v4
      